http:
    middlewares:
        example-redirect:
            plugin:
                uaredirect:
                    url: https://www.google.com
                    useragent: Example Agent 1.0
    routers:
        example:
            entrypoints: web
            middlewares: example-redirect
            rule: Host(`callback.example.com`)
            service: example-svc
    services:
        example-svc:
            loadbalancer:
                servers:
                    - url: http://10.10.10.10:5000
